### ISSUE TITLE
[idea] [shortener-list] what about a "shorten ls" command?

### ISSUE THREAD

**Issue by horacioh** [kentcdodds/netlify-shortener#16]
Problem description:
My memory is really bad, so I think I will need to check my shortener list when people ask me for stuff. maybe it would be nice to expose a `list` option so all the shortcodes can be listed on my terminal?

Suggested solution:

run this command:

```bash
netlify-shortener ls
```

will list all the shortcodes available on your `_redirects` file

```bash
foo
bar
baz
example
*
```

I made a simple prototype but wanted to see if there's any interest before I invest more time on it. :)

It could be also a shortcode for `cat _redirects`...

**Comment by kentcdodds** [comment]
Thanks for the idea. I have a similar problem and all I do is I have a shortened URL at https://kcd.im/shorten which takes me to https://github.com/kentcdodds/kcd.im/edit/master/_redirects then I can look at what's in that file to know what URLs I have:

![image](https://user-images.githubusercontent.com/1500684/64723531-ee008700-d48d-11e9-8e05-468b4a02674b.png)

> It could be also a shortcode for `cat _redirects`

If you really want to do this locally, then I'd recommend just doing `cat _redirects` as you suggest. Adding complexity for this package is not really justified because it's so easy to review the list in conventional ways.

Thanks though!
